### ISSUE TITLE
7536 colours

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-defakts#13]
**URL:**
https://defakts-plattform.de/
https://defakts-dev.liqd.net/
https://defakts-stage.liqd.net/
**user:** 
**expected behaviour:** 
defakts colours in use on dev, stage and prod, also in mailings
colours meet a11y requirements (contrast)
**behaviour:**
No black on stage and prod
Light orange and white font in dropdown not readable
User icons still use a+ colours
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
<img width="358" alt="image" src="https://github.com/liqd/a4-defakts/assets/94360651/6508bb0c-e92f-4635-86da-b6ba3872f74d">

<img width="370" alt="image" src="https://github.com/liqd/a4-defakts/assets/94360651/cce3e605-144b-4795-b9fc-774490b595d8">

<img width="685" alt="image" src="https://github.com/liqd/a4-defakts/assets/94360651/b0ce92b1-de8a-4e3a-a2f7-4718009b2db9">

**Comment by maxliqd** [comment]
@mcastro-lqd Can you create a design or name the colours for the registration drop-down?

**Comment by maxliqd** [comment]
I saw that the dropdown was already fixed, thank you. Do you need more information for the colours of the user icons?

**Comment by maxliqd** [comment]
@mcastro-lqd Can you take a look at this issue and tell me if the user icons need colour changes? Thanks!

**Comment by mcastro-lqd** [comment]
Oh, I forgot about that Sorry! liquid-designer/Nextcloud/Projekte/DeFaktS/00 Archiv/Material/Avatar

**Comment by maxliqd** [comment]
Moved it here to folder Kreation: /Nextcloud/Projekte/DeFaktS/Kreation/Avatar
