### ISSUE TITLE
registration mailing prod

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-defakts#15]
**URL:** defakts-plattform.de
**user:** person who registers
**expected behaviour:** in the mailing the right name of the platform is used
**behaviour:** example.com is used
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by philli-m** [comment]
@maxliqd I deleted the image as it had your email address, wasn't sure if you knew but I also think this is a site setting, maybe in wagtail?! will check it out

**Comment by maxliqd** [comment]
@philli-m Thanks, found it in the settings on Wagtail!
