### ISSUE TITLE
font for tabs has shadow and wrong colour when no picture is added

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-defakts#29]
**URL:** https://defakts-dev.liqd.net/defakts-testorganisation/projects/hannes-test-project/
**user:** 
**expected behaviour:** black font, no shadow
**behaviour:** gray font, shadow
**important screensize:**
**device & browser:** firefox, chrome
**Comment/Question:** 

Screenshot?
![image](https://github.com/liqd/a4-defakts/assets/94360651/6536836b-7a62-4494-9e36-ac6efda96f54)

**Comment by goapunk** [comment]
will be fixed once rebased on a+

**Comment by philli-m** [comment]
done
