### ISSUE TITLE
info about char limit for user reports, long user reports cannot be saved.

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-defakts#36]
**URL:** https://defakts-dev.liqd.net/defakts-testorganisation/subjects/2023-00001/
**user:**  participant
**expected behaviour:** As a user, I can write a text that fits the text field. Either there is info about a char limit or the field has no char limit but I can save it. In this case the info would be preferable, because reports should not be too long.
**behaviour:** Users cannot save reports that are too long, but do not get a hint or an error message.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
900 characters seem to be the limit.

Screenshot?

**Comment by goapunk** [comment]
we should probably fix this in a+ / a4 and it will then come to defakts after rebasing

**Comment by maxliqd** [comment]
Ok, shall I move the issue to the a4 repo?

**Comment by CarolingerSeilchenspringer** [comment]
@pascalkienast @sblindow can one of you check if this is fixed in a+? And if not, write an issue in a+ and close this issue here with a link to the new issue? Thanks!

**Comment by goapunk** [comment]
@CarolingerSeilchenspringer @pascalkienast @sblindow it's not fixed. We do need a new wording for the report modal which includes the character limit

**Comment by goapunk** [comment]
opened https://github.com/liqd/adhocracy4/issues/1634 in a4, leaving this open as reminder for now

**Comment by CarolingerSeilchenspringer** [comment]
@goapunk change via mB so will close here.
