### ISSUE TITLE
Front-end Issues 

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/a4-defakts#38]
**URL:** https://defakts-dev.liqd.net
**important screensize:** *Both*
**device & browser:** *Safari and Chrome*
**Comment/Question:** *Sorry it took so long, but here are some errors I found in Defakts. I decided to put everything on a pdf to make it faster.* 

[test-defakts.pdf](https://github.com/liqd/a4-defakts/files/12785244/test-defakts.pdf)

**Comment by philli-m** [comment]
- [ ] 01 org name tab styling
- [ ] tab shadow
- [ ] transparent button behaviour
- [ ] rating button colours to be changed
- [ ] comment button behaviour?
- [ ] padding mod button
- [ ] close button on mob
- [ ] bg blocks full width mobile
- [ ] mod feedback on mobilie

**Comment by philli-m** [comment]
@mcastro-lqd i'm not sure which 'dark one' button you are referring to in 03? also not sure what you mean by 'highlighted a bit'? sorry!

**Comment by philli-m** [comment]
@mcastro-lqd thanks for the clarifications, as that element uses the same button as the lighter background components this needs a template refactor so will add it to a separate issue and remove from the milestone for now just dues to time pressure, sorry!
