### ISSUE TITLE
internal server error 500 link leads to a+

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-defakts#46]
**URL:** defakts-stage.liqd.net
**user:**
**expected behaviour:** link leads back to a relevant website (either a working defakts stage site or a liqd.net)
**behaviour:** links to adhocracy.plus
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by goapunk** [comment]
should probably be fixed in a+
