### ISSUE TITLE
change wording for toggle switch on moderation dashboard

### ISSUE THREAD

**Issue by maxliqd** [liqd/a4-defakts#48]
**URL:** defakts-dev.liqd.net and defakts-stage.liqd.net
**user:** moderator
**expected behaviour:** Moderators know which content will be hidden from or added to discussion: only the XAI content.
**behaviour:** The wording "Show info to users" could apply to user reports above the red line and XAI content. Wording should be "Show AI info to users"
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

![image](https://github.com/liqd/a4-defakts/assets/94360651/65bd510c-558c-4704-8b17-baeca0a44093)

**Comment by goapunk** [comment]
fixed in a4
